version: '3'

services:
  store-database: 
    image: postgres:latest 
    container_name: store-database
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - store-network

  store-maanager:
    container_name: store-manager
    hostname: "${HOSTNAME}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/project
    command: >
      bash -c "
        curl -fsSL https://deb.nodesource.com/setup_21.x | bash - &&
        apt-get install -y nodejs &&
        python manage.py runserver ${HOSTNAME}:${PORT}
      "
    volumes:
      - ./project/:/usr/src/project
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
      - DEBUG=true
    env_file:
      .env
    depends_on:
      - store-database
    networks:
      - store-network

networks:
    store-network:
        external: true
