# Generated by Django 5.0 on 2025-02-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Computador'), ('O', 'Outro'), ('T', 'Tablet'), ('S', 'Smartvideo')], default='O', max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.tipoproduto'),
            preserve_default=False,
        ),
    ]
