# Generated by Django 5.0 on 2025-02-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tipoproduto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproduto',
            name='tipo',
            field=models.CharField(choices=[('ALI', 'Alimento'), ('SOB', 'Sobremesa'), ('ELE', 'Eletrônico')], default='-', max_length=3, unique=True),
        ),
    ]
